languageCode = "ja-jp"
title = "Parakeety's Blog"
theme = "pickles"
baseURL = "https://parakeety.github.io/"
googleAnalytics = "{UA-64117421-1}"

[params]
  paginate = 10
  github = "parakeety"
  name = "parakeety"
  author = "parakeety"
  authorwebsite = "http://www.parakeety.com/"
  bio = "Software Engineer at Mercari"
  subtitle = "iOS, Golang, and Cryptocurrency"
