languageCode = "ja-jp"
title = "Parakeety's Blog"
theme = "pickles"

[params]
  paginate = 10
  github = "parakeety"
  author = "parakeety"
  authorwebsite = "http://www.parakeety.com/"
  bio = "Software Engineer at Mercari"
  subtitle = "iOS, Golang, and Cryptocurrency"
